name: CI
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          source-folder: .
          git-user: liam-lai
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
